# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
draw_hX <- function(s, y, phi, sigma2, mu, X, beta) {
    .Call('_svmod_draw_hX', PACKAGE = 'svmod', s, y, phi, sigma2, mu, X, beta)
}

#' @export
draw_s <- function(y, h) {
    .Call('_svmod_draw_s', PACKAGE = 'svmod', y, h)
}

timesTwo <- function(x) {
    .Call('_svmod_timesTwo', PACKAGE = 'svmod', x)
}

#' @export
chol_Eigen <- function(M) {
    .Call('_svmod_chol_Eigen', PACKAGE = 'svmod', M)
}

#' @export
inv_Eigen <- function(M) {
    .Call('_svmod_inv_Eigen', PACKAGE = 'svmod', M)
}

#' @export
dgemv <- function(A, x, y) {
    invisible(.Call('_svmod_dgemv', PACKAGE = 'svmod', A, x, y))
}

#' @export
dpbtrf <- function(A, N) {
    invisible(.Call('_svmod_dpbtrf', PACKAGE = 'svmod', A, N))
}

#' @export
dtbtrs <- function(A, x, ND) {
    invisible(.Call('_svmod_dtbtrs', PACKAGE = 'svmod', A, x, ND))
}

#' @export
dtbtrsT <- function(A, x, ND) {
    invisible(.Call('_svmod_dtbtrsT', PACKAGE = 'svmod', A, x, ND))
}

#' @export
dsbmv <- function(A, x, N) {
    invisible(.Call('_svmod_dsbmv', PACKAGE = 'svmod', A, x, N))
}

#' @export
UBMV <- function(v, phi, sigma2) {
    invisible(.Call('_svmod_UBMV', PACKAGE = 'svmod', v, phi, sigma2))
}

