# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
draw_s_cpp <- function(y, h) {
    .Call('_svmod_draw_s_cpp', PACKAGE = 'svmod', y, h)
}

#' @export
draw_h_cpp <- function(y, s, phi, sigma2, mu) {
    .Call('_svmod_draw_h_cpp', PACKAGE = 'svmod', y, s, phi, sigma2, mu)
}

#' @export
draw_theta_cpp <- function(h0, h, mu, phi, sigma, Bsigma, a0, b0, bmu, Bmu, B011inv, B022inv) {
    .Call('_svmod_draw_theta_cpp', PACKAGE = 'svmod', h0, h, mu, phi, sigma, Bsigma, a0, b0, bmu, Bmu, B011inv, B022inv)
}

draw_theta_cpp_test <- function(h0, h, mu, phi, sigma, Bsigma, a0, b0, bmu, Bmu, B011inv, B022inv) {
    .Call('_svmod_draw_theta_cpp_test', PACKAGE = 'svmod', h0, h, mu, phi, sigma, Bsigma, a0, b0, bmu, Bmu, B011inv, B022inv)
}

#' @export
draw_hX_cpp <- function(y, s, X, beta, phi, sigma2, mu) {
    .Call('_svmod_draw_hX_cpp', PACKAGE = 'svmod', y, s, X, beta, phi, sigma2, mu)
}

#' @export
test_LAPACK <- function(s, y, phi, sigma2, mu) {
    .Call('_svmod_test_LAPACK', PACKAGE = 'svmod', s, y, phi, sigma2, mu)
}

#' @export
invGamme_cpp <- function(cT, CT) {
    .Call('_svmod_invGamme_cpp', PACKAGE = 'svmod', cT, CT)
}

#' @export
inv_Eigen <- function(M) {
    .Call('_svmod_inv_Eigen', PACKAGE = 'svmod', M)
}

#' @export
chol_Eigen <- function(M) {
    .Call('_svmod_chol_Eigen', PACKAGE = 'svmod', M)
}

#' @export
eigen_mult <- function(A, X) {
    .Call('_svmod_eigen_mult', PACKAGE = 'svmod', A, X)
}

#' @export
diagonal <- function(x) {
    .Call('_svmod_diagonal', PACKAGE = 'svmod', x)
}

#' @export
solve_tri <- function(A, b) {
    .Call('_svmod_solve_tri', PACKAGE = 'svmod', A, b)
}

#' @export
chol_sparse <- function(A) {
    .Call('_svmod_chol_sparse', PACKAGE = 'svmod', A)
}

